# Generated by Django 3.2.7 on 2021-09-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userpic',
            field=models.ImageField(blank=True, upload_to='usr/%y'),
        ),
    ]
