# Generated by Django 3.2.7 on 2021-09-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_user_userpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
